### PR TITLE
application developers' guide introduction: restore list items

### PR DESCRIPTION
**Pull request by ronaldomercado**
This restores list items (bullet points) shown on page 16 & 17 from the online pdf
https://epics.anl.gov/base/R3-16/2-docs/AppDevGuide.pdf 
(section 2.5)

### CODE REVIEW

**Comment by simon-ess** [comment]
This doesn't seem to be working as expected: see https://epics--19.org.readthedocs.build/en/19/appdevguide/gettingStarted.html#building-ioc-components which shows a very different layout.

**Comment by minijackson** [comment]
I think this is unrelated to this PR. We're going to figure out why the local build and the RtD build have different CSS

**Comment by minijackson** [comment]
Could you also make definition lists out of the other specifications?

For turning this:

```rst
| ``include``
| C include files are installed here. Either header files supplied by
  the application or header files generated from ``xxxRecord.dbd`` or
  ``xxxMenu.dbd`` files.
```

into this:

```rst
``include``
  C include files are installed here. Either header files supplied by
  the application or header files generated from ``xxxRecord.dbd`` or
  ``xxxMenu.dbd`` files.
```

It seems like they were definition lists in the [original HTML](https://epics.anl.gov/base/R3-15/5-docs/AppDevGuide/GettingStarted.html#x3-160002.5), and it might look better in Read the Docs

**Comment by ronaldomercado** [comment]
Thanks @minijackson and @simon-ess for the comments.
I have created definition lists as suggested.

**Review by minijackson — APPROVED** [review]
I think it looks good

**Pull request merged**
