### PR TITLE
chore(deps): make requirements-dev.txt coherent with the rest

### PR DESCRIPTION
**Pull request by minijackson**
I forgot this file when doing #61

### CODE REVIEW

**Comment by minijackson** [comment]
This file is the reason we still have a dependabot alert: https://github.com/epics-docs/epics-docs/security/dependabot/5

I think we should configure dependabot so that it automatically does these kinds of pull requests

**Comment by ralphlange** [comment]
Cross-checked with yesterday's commits: all good!

**Comment by ralphlange** [comment]
> I think we should configure dependabot so that it automatically does these kinds of pull requests

Would that also work for `requirements-dev.txt`?

**Comment by minijackson** [comment]
I think it does? I've seen that dependabot supports `requirements.txt` files, and the dependabot alert does mention `requirements-dev.txt`.

**Pull request merged**
