### PR TITLE
Fix Poetry dependencies with sphing-tags

### PR DESCRIPTION
**Pull request by minijackson**
I've also added a section in CONTRIBUTING for how to add dependencies.

Maybe we should migrate the Read the Docs build to use Poetry? This would avoid issues like this.

CC @ttkorhonen @ralphlange @mnabywan

### CODE REVIEW

**Comment by mnabywan** [comment]
Thank you for the fixes! <br/>
I think that using `poetry` can be a good idea but no sure because I guess people are more familiar with installing requirements with `pip`.

**Comment by ralphlange** [comment]
Thanks a lot - works like a charm!

**Comment by ttkorhonen** [comment]
If Poetry works on RTD (I believe it will), it would be transparent for most users; the RTD build process should only be customised by a few selected people. For local installations people can still select if they use pip or Poetry. I started with pip and have been using it still, but may switch to Poetry at some stage.

**Comment by minijackson** [comment]
There's this bit from the doc: https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

Although, that would mean Read the Docs must not use `requirements.txt` anymore, so if we don't remove it then, we will have the same problem (two ways of specifying dependencies), but in reverse.

**Comment by ralphlange** [comment]
Btw.
The `poetry run sphinx-autobuild ...` continuously loops on
```
[sphinx-autobuild] Detected change: /mnt/.../epics-docs/_tags/advanced.md
```
which is probably regenerated as part of the build.
I can fix this by specifying `--re-ignore _tags/`.
(The `--ignore` globs only match file names, not directories.)

I will push a fix to the contribution guide in a sec.

**Pull request merged**
