### PR TITLE
add msi documentation and references to it in the build system doc

### PR DESCRIPTION
**Pull request by ttkorhonen**
Added documentation for msi (Macro Substitution tool), written by Marty Kraimer. Referred to it in the Build Facility text.

### CODE REVIEW

**Comment by ttkorhonen** [comment]
If somebody reviews...I did not put msi in the top level navigation menus. It can be found in the "Build Facility" chapter, as a refefence and as an appendix in the end of the same doc.

**Comment by anjohnson** [comment]
The original for this document is included in the epics-base sources but [as an HTML file](https://github.com/epics-base/epics-base/blob/7.0/modules/database/src/ioc/dbtemplate/msi.html). We've been trying to put/keep documentation sources in the same place as the code they describe so that a single PR can edit both at the same time, and I would prefer that your .md file replace that .html one instead of being added here. Change the adjacent Makefile line
```patch
-HTMLS += msi.html
+DOCS += msi.md
```
to install the file so the RTD build will find it. I'm not sure if are any other changes would be needed to the base RTD config though.

**Comment by ttkorhonen** [comment]
All right, will do that. I needed to consult the msi documentation and had a bit of time available so I converted the HTML to md. I would like to link to this from other places though, but I think I can find a way to do it without hard-coding the path.

**Comment by ttkorhonen** [comment]
Replaced with a PR to epics-base.  Closing this PR.

**Pull request closed without merging**
