### PR TITLE
Add extra labels configuration to indicate the audience

### PR DESCRIPTION
**Pull request by mnabywan**
Idea: make possible to mark pages with extra labels for example to idicate the audience. <br/>
For now in conf.py I specified audience to 'advanced', 'developers', 'users', 'beginners', 'all'.

### CODE REVIEW

**Comment by gabrielfedel** [comment]
@mnabywan there are some conflicts to be solved here

**Comment by gabrielfedel** [comment]
@mnabywan I got an error trying to build: 
`Could not import extension epics_docs_ext.extra_labels (exception: No module named 'epics_docs_ext')`

Is there something missing on requirements.txt ? or the problem is on my environment ?

**Comment by stephane-cea** [comment]
I like a lot the idea to have those labels. I think the ones you proposed are fine ('advanced', 'developers', 'users', 'beginners', 'all'), we probably don't need more.

It would be also very nice to have a mention somewhere in the [Documentation contribution guide](https://epics--35.org.readthedocs.build/en/35/CONTRIBUTING.html), reminding contributors to specify label(s) when creating a new page (or when editing a page that still has no label yet).

**Comment by mnabywan** [comment]
Yes, I will mention that in contribution guide

**Comment by gabrielfedel** [comment]
LGTM! I did a quick review of the way you marked the pages and it looks fine to me

**Comment by ralphlange** [comment]
Are the audience labels explained somewhere?
I think in our case the terms "user" and "developer" might be a bit ambiguous.

Of the three use cases:
- operator in the control room
- controls person creating an IOC application (including Stream protocol)
- controls person writing or changing a Device Support module

Who is a user and who is a developer?

**Comment by gabrielfedel** [comment]
I would say that operator would be the user, and the other 2 developer. But maybe with an explanation on CONTRIBUTING file this is solved.

**Comment by mnabywan** [comment]
Yes, that's a good proposition. For me it's also difficult to differ developer from user when we discuss a person running a simple IOC. I will include that in contribution guide. <br/>
Also, it would be good to check my labels put on single documents as I have chosen the first idea for whom is the single document

**Comment by ralphlange** [comment]
The big and probably only part that is exclusive for code developers and not relevant for application developers: the reference of the C/C++ APIs of Base.

**Comment by stephane-cea** [comment]
I fetch the PR locally (`git fetch origin pull/35/head:labels && git switch labels`) and tried it out.

It works very well, and is really nice to have! This is great work.

Now here are my thoughts about this:

It appears that a full sphinx extension has been implemented in Python (located in the `epics_docs_ext` directory) in order to have this feature. This implies to maintain the associated code in addition to the existing documentation, which can be time-consuming down the line. I think that before committing to this solution, we should just make sure to avoid re-inventing the wheel.

I found a project called [sphinx-tags](https://sphinx-tags.readthedocs.io/en/latest/quickstart.html), and it seems to do what this PR is trying to achieve.

Is there any reason to implement our own sphinx extension instead of using [sphinx-tags](https://sphinx-tags.readthedocs.io/en/latest/quickstart.html)? I'm genuinely asking, because maybe I'm missing something.

**Comment by mnabywan** [comment]
Oh, really I didn't found that before. I think that would looks really good. <br/>
The only difference is that here we can put extra labels in groups - in current config we have only audition and we have labels for it. If we want we can add next group of labels by for example by maintainer.

Nevertheless, I will try to use that as it will simplify a lot and will be enough.

**Comment by mnabywan** [comment]
Hey, I tried sphinx-tags` and looks good and is much simpler. I open another MR and close that one.

Check: https://github.com/epics-docs/epics-docs/pull/52

**Pull request closed without merging**
