### PR TITLE
Include posix threads priorities scheduling on linux

### PR DESCRIPTION
**Pull request by gabrielfedel**
Copied from
https://epics-controls.org/resources-and-support/documents/howto-documents/posix-thread-priority/

This PR is part of the effort to migrate how-to section from https://epics-controls.org

### CODE REVIEW

**Comment by gabrielfedel** [comment]
This PR is ready to be reviewed but I'm not sure where put it , right now it is under a howto folder and is not included on index.rst. Suggestions are welcome.

**Comment by gabrielfedel** [comment]
I have added semantic line breaks to this one to check if I understood the concept

**Comment by ttkorhonen** [comment]
Could the index.rst be removed from this PR? The navigation has been modified and index.rst conflicts with the new situation. I would rather merge this without the index and adjust the navigation in a separate PR.

**Comment by ttkorhonen** [comment]
@gabrielfedel , I guess is it OK to remove index.rst from this PR? The navigation has been changed a lot and index.rst conflicts with the current status.

**Comment by ttkorhonen** [comment]
Thanks @gabrielfedel , I will merge this right away!

**Comment by ttkorhonen** [comment]
Not yet included in the index, but you can access it via https://docs.epics-controls.org/en/latest/build-system/posix-threads-priority-scheduling-linux.html
I will add it to the navigation later (today, I hope)

**Pull request merged**
